# Generated by Django 5.1.1 on 2024-09-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='location_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
