# Generated by Django 5.1.1 on 2024-09-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_shopify', '0002_store_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAliexpressIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=50)),
                ('shopifyOrder', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('freight', models.CharField(blank=True, max_length=70)),
                ('code_track', models.CharField(blank=True, max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
