# Generated by Django 5.1.1 on 2024-10-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_shopify', '0004_shopifyaliexpressintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
